/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './footer.component';
const styles_skmFooterComponent:any[] = ['.footer[_ngcontent-%COMP%]{\n              position: absolute;\n              right: 0;\n              bottom: 0;\n              left: 0;\n              padding: 1rem;\n              background-color: #efefef;\n              text-align: center;\n              background-color: darkred;\n              color: orange\n            }'];
export const RenderType_skmFooterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_skmFooterComponent,data:{}});
export function View_skmFooterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n                '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),7,'footer',[['class','footer']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n                  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',
      [['class','container']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n                    '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'p',[['class','text-muted']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['Copyright skmprintings @ 2017.'])),(_l()(),i0.ɵted((null as any),['\n                  '])),
      (_l()(),i0.ɵted((null as any),['\n                '])),(_l()(),i0.ɵted((null as any),
          ['\n            ']))],(null as any),(null as any));
}
export function View_skmFooterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-footer',([] as any[]),
      (null as any),(null as any),(null as any),View_skmFooterComponent_0,RenderType_skmFooterComponent)),
      i0.ɵdid(49152,(null as any),0,i1.skmFooterComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const skmFooterComponentNgFactory:i0.ComponentFactory<i1.skmFooterComponent> = i0.ɵccf('skm-footer',
    i1.skmFooterComponent,View_skmFooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvZm9vdGVyL2Zvb3Rlci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvZm9vdGVyL2Zvb3Rlci5jb21wb25lbnQudHMiLCJuZzovLy9DOi9wZXJzb25hbC9za20vYXNzZXRzL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC50cy5za21Gb290ZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50LnRzLnNrbUZvb3RlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICAgICAgICAgIDxmb290ZXIgY2xhc3M9XCJmb290ZXJcIj5cbiAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICAgICAgICAgICAgICAgICAgPHAgY2xhc3M9XCJ0ZXh0LW11dGVkXCI+Q29weXJpZ2h0IHNrbXByaW50aW5ncyBAIDIwMTcuPC9wPlxuICAgICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICAgICAgPC9mb290ZXI+XG4gICAgICAgICAgICAiLCI8c2ttLWZvb3Rlcj48L3NrbS1mb290ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsdURBQ2dCO2FBQUE7VUFBQSwwREFBdUI7TUFBQSwyQkFDckI7TUFBQTtNQUFBLGdCQUF1QiwyREFDckI7YUFBQTtVQUFBLDBEQUFzQjtNQUFBLHFDQUFrQztNQUNwRCx1REFDQztVQUFBOzs7b0JDTHpCO01BQUE7YUFBQTtVQUFBOzs7In0=
