/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './menu.component';
const styles_skmMenuComponent:any[] = [''];
export const RenderType_skmMenuComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_skmMenuComponent,data:{}});
export function View_skmMenuComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',[['style','width:40%; background-color:\'red\'']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['Hello']))],(null as any),(null as any));
}
export function View_skmMenuComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-menu',([] as any[]),
      (null as any),(null as any),(null as any),View_skmMenuComponent_0,RenderType_skmMenuComponent)),
      i0.ɵdid(49152,(null as any),0,i1.skmMenuComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const skmMenuComponentNgFactory:i0.ComponentFactory<i1.skmMenuComponent> = i0.ɵccf('skm-menu',
    i1.skmMenuComponent,View_skmMenuComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYmFzZS9tZW51L21lbnUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL2Jhc2UvbWVudS9tZW51LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL2Jhc2UvbWVudS9tZW51LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYmFzZS9tZW51L21lbnUuY29tcG9uZW50LnRzLnNrbU1lbnVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8IS0tdWw+XHJcbiAgICA8bGk+XHJcbiAgICAgICAgPHVsPlxyXG4gICAgICAgICAgICA8bGk+RGVzaWduIHlvdSBvd248L2xpPlxyXG4gICAgICAgICAgICA8bGk+VHJhY2sgeW91ciBvcmRlcjwvbGk+XHJcbiAgICAgICAgPC91bD4gICAgICAgIFxyXG4gICAgPC9saT5cclxuPC91bD5cclxuXHJcbjx1bD5cclxuICAgPGxpPlxyXG4gICAgICAgPHVsPlxyXG4gICAgICAgICAgIDxsaT5QYXBlciBDYXJkczwvbGk+XHJcbiAgICAgICAgICAgPGxpPkNsb3RoZXM8L2xpPiAgICAgICAgICAgXHJcbiAgICAgICA8L3VsPlxyXG4gICA8L2xpPlxyXG48L3VsPlxyXG5cclxuPHVsPlxyXG4gICAgPGxpPlxyXG4gICAgICAgIDx1bD5cclxuICAgICAgICAgICAgPGxpPk90aGVyIHNlcnZpY2VzPC9saT5cclxuICAgICAgICAgICAgPGxpPkFib3V0IHVzPC9saT5cclxuICAgICAgICA8L3VsPlxyXG4gICAgPC9saT5cclxuPC91bC0tPlxyXG48ZGl2IHN0eWxlPVwid2lkdGg6NDAlOyBiYWNrZ3JvdW5kLWNvbG9yOidyZWQnXCI+SGVsbG88L2Rpdj4iLCI8c2ttLW1lbnU+PC9za20tbWVudT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkN5Qk8sdUNBQ1A7TUFBQTtNQUFBLDBEQUErQztNQUFBOzs7b0JDMUIvQztNQUFBO2FBQUE7VUFBQTs7OyJ9
