/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './carousel/carousel.component.ngfactory';
import * as i2 from './carousel/carousel.component';
import * as i3 from './news/news.component.ngfactory';
import * as i4 from './news/news.component';
import * as i5 from './home.component';
const styles_skmHomeComponent:any[] = ([] as any[]);
export const RenderType_skmHomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_skmHomeComponent,data:{}});
export function View_skmHomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'flex-box']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['   \n    '])),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),4,'div',[['class','center-align']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['        \n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,
          'skm-carousel',([] as any[]),(null as any),(null as any),(null as any),i1.View_skmCarouselComponent_0,
          i1.RenderType_skmCarouselComponent)),i0.ɵdid(49152,(null as any),0,i2.skmCarouselComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['    \n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n'])),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),4,'div',[['style','height:220px']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-news',
          ([] as any[]),(null as any),(null as any),(null as any),i3.View_skmNewsComponent_0,
          i3.RenderType_skmNewsComponent)),i0.ɵdid(49152,(null as any),0,i4.skmNewsComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_skmHomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-home',([] as any[]),
      (null as any),(null as any),(null as any),View_skmHomeComponent_0,RenderType_skmHomeComponent)),
      i0.ɵdid(49152,(null as any),0,i5.skmHomeComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const skmHomeComponentNgFactory:i0.ComponentFactory<i5.skmHomeComponent> = i0.ɵccf('skm-home',
    i5.skmHomeComponent,View_skmHomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYmFzZS9ob21lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9wZXJzb25hbC9za20vYXNzZXRzL2FwcC9iYXNlL2hvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYmFzZS9ob21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYmFzZS9ob21lLmNvbXBvbmVudC50cy5za21Ib21lQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImZsZXgtYm94XCI+ICAgXHJcbiAgICA8IS0tc2ttLW1lbnU+PC9za20tbWVudS0tPlxyXG4gICAgPCEtLWRpdj5cclxuICAgICAgICA8Zm9ybSAobmdTdWJtaXQpPVwib25TdWJtaXQoZilcIiAjZj1cIm5nRm9ybVwiPlxyXG4gICAgICAgICAgIDxkaXYgY2xhc3M9XCJmb3JtLWdyb3VwXCI+XHJcbiAgICAgICAgICAgICAgIDxpbnB1dCBcclxuICAgICAgICAgICAgICAgICAgICAgICB0eXBlPVwidGV4dFwiIFxyXG4gICAgICAgICAgICAgICAgICAgICAgIGlkPVwiY29udGVudFwiXHJcbiAgICAgICAgICAgICAgICAgICAgICAgY2xhc3M9XCJmb3JtLWNvbnRyb2xcIiBcclxuICAgICAgICAgICAgICAgICAgICAgICBuZ01vZGVsIFxyXG4gICAgICAgICAgICAgICAgICAgICAgIG5hbWU9XCJjb250ZW50XCIgXHJcbiAgICAgICAgICAgICAgICAgICAgICAgcmVxdWlyZWQ+XHJcbiAgICAgICAgICAgPC9kaXY+XHJcbiAgICAgICAgICAgPGJ1dHRvbiB0eXBlPVwic3VibWl0XCI+c2F2ZTwvYnV0dG9uPlxyXG4gICAgICAgIDwvZm9ybT5cclxuICAgIDwvZGl2LS0+XHJcbiAgICA8ZGl2IGNsYXNzPVwiY2VudGVyLWFsaWduXCI+ICAgICAgICBcclxuICAgICAgICA8c2ttLWNhcm91c2VsPjwvc2ttLWNhcm91c2VsPiAgICBcclxuICAgIDwvZGl2PlxyXG4gICAgPCEtLXNrbS1hZEJsb2NrPjwvc2ttLWFkQmxvY2stLT5cclxuPC9kaXY+XHJcbjxkaXYgc3R5bGU9XCJoZWlnaHQ6MjIwcHhcIj5cclxuICAgIDxza20tbmV3cz48L3NrbS1uZXdzPlxyXG48L2Rpdj4iLCI8c2ttLWhvbWU+PC9za20taG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFzQiw4Q0FDUTtVQUFBLGFBY2xCLDJDQUNSO1VBQUE7VUFBQSwwREFBMEI7VUFBQSx5QkFDdEI7VUFBQTs0Q0FBQSxVQUFBO1VBQUEsMkNBQTZCO1VBQUEsaUJBQzNCLDJDQUMwQjtVQUFBLFNBQzlCLHVDQUNOO1VBQUE7VUFBQSw0Q0FBMEI7VUFBQSxhQUN0QjtVQUFBO3dDQUFBLFVBQUE7VUFBQSwyQ0FBcUI7VUFBQTs7O29CQ3RCekI7TUFBQTthQUFBO1VBQUE7OzsifQ==
