/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './adblock.component';
const styles_skmAdBlockComponent:any[] = ['.ad-block[_ngcontent-%COMP%]{\n                border: 2px solid grey;\n                width: 15%\n                height: 80%;\n            }'];
export const RenderType_skmAdBlockComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_skmAdBlockComponent,data:{}});
export function View_skmAdBlockComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'ad-block']],(null as any),(null as any),(null as any),(null as any),(null as any)))],
      (null as any),(null as any));
}
export function View_skmAdBlockComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-adBlock',
      ([] as any[]),(null as any),(null as any),(null as any),View_skmAdBlockComponent_0,
      RenderType_skmAdBlockComponent)),i0.ɵdid(49152,(null as any),0,i1.skmAdBlockComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const skmAdBlockComponentNgFactory:i0.ComponentFactory<i1.skmAdBlockComponent> = i0.ɵccf('skm-adBlock',
    i1.skmAdBlockComponent,View_skmAdBlockComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYmFzZS9hZEJsb2NrL2FkYmxvY2suY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL2Jhc2UvYWRCbG9jay9hZGJsb2NrLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL2Jhc2UvYWRCbG9jay9hZGJsb2NrLmNvbXBvbmVudC50cy5za21BZEJsb2NrQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9wZXJzb25hbC9za20vYXNzZXRzL2FwcC9iYXNlL2FkQmxvY2svYWRibG9jay5jb21wb25lbnQudHMuc2ttQWRCbG9ja0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJhZC1ibG9ja1wiPjwvZGl2PiIsIjxza20tYWRCbG9jaz48L3NrbS1hZEJsb2NrPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7Ozs7b0JDQUE7TUFBQTtvQ0FBQSxVQUFBO01BQUE7OzsifQ==
