/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './login.component';
const styles_skmLoginComponent:any[] = ([] as any[]);
export const RenderType_skmLoginComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_skmLoginComponent,data:{}});
export function View_skmLoginComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n                '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['login'])),(_l()(),i0.ɵted((null as any),['\n            ']))],(null as any),
      (null as any));
}
export function View_skmLoginComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-login',([] as any[]),
      (null as any),(null as any),(null as any),View_skmLoginComponent_0,RenderType_skmLoginComponent)),
      i0.ɵdid(49152,(null as any),0,i1.skmLoginComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const skmLoginComponentNgFactory:i0.ComponentFactory<i1.skmLoginComponent> = i0.ɵccf('skm-login',
    i1.skmLoginComponent,View_skmLoginComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvdXNlci9sb2dpbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvdXNlci9sb2dpbi5jb21wb25lbnQudHMiLCJuZzovLy9DOi9wZXJzb25hbC9za20vYXNzZXRzL2FwcC91c2VyL2xvZ2luLmNvbXBvbmVudC50cy5za21Mb2dpbkNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvdXNlci9sb2dpbi5jb21wb25lbnQudHMuc2ttTG9naW5Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgICAgICAgICA8aDE+bG9naW48L2gxPlxuICAgICAgICAgICAgIiwiPHNrbS1sb2dpbj48L3NrbS1sb2dpbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSx1REFDZ0I7YUFBQTtVQUFBLDRDQUFJO01BQUEsWUFBVTs7OztvQkNEOUI7TUFBQTthQUFBO1VBQUE7OzsifQ==
