/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
const styles_skmLogOutComponent:any[] = ([] as any[]);
export const RenderType_skmLogOutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_skmLogOutComponent,data:{}});
export function View_skmLogOutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n                '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['sign out'])),(_l()(),i0.ɵted((null as any),['\n            ']))],(null as any),
      (null as any));
}
export function View_skmLogOutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-signout',
      ([] as any[]),(null as any),(null as any),(null as any),View_skmLogOutComponent_0,
      RenderType_skmLogOutComponent)),i0.ɵdid(49152,(null as any),0,i1.skmLogOutComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const skmLogOutComponentNgFactory:i0.ComponentFactory<i1.skmLogOutComponent> = i0.ɵccf('skm-signout',
    i1.skmLogOutComponent,View_skmLogOutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvdXNlci9sb2dvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL3VzZXIvbG9nb3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL3VzZXIvbG9nb3V0LmNvbXBvbmVudC50cy5za21Mb2dPdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL3VzZXIvbG9nb3V0LmNvbXBvbmVudC50cy5za21Mb2dPdXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgICAgICAgICA8aDE+c2lnbiBvdXQ8L2gxPlxuICAgICAgICAgICAgIiwiPHNrbS1zaWdub3V0Pjwvc2ttLXNpZ25vdXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsdURBQ2dCO2FBQUE7VUFBQSw0Q0FBSTtNQUFBLGVBQWE7Ozs7b0JDRGpDO01BQUE7bUNBQUEsVUFBQTtNQUFBOzs7In0=
