/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './signup.component';
const styles_skmSignUpComponent:any[] = ([] as any[]);
export const RenderType_skmSignUpComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_skmSignUpComponent,data:{}});
export function View_skmSignUpComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n                '])),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['sign up'])),(_l()(),i0.ɵted((null as any),['\n            ']))],(null as any),
      (null as any));
}
export function View_skmSignUpComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-signup',([] as any[]),
      (null as any),(null as any),(null as any),View_skmSignUpComponent_0,RenderType_skmSignUpComponent)),
      i0.ɵdid(49152,(null as any),0,i1.skmSignUpComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const skmSignUpComponentNgFactory:i0.ComponentFactory<i1.skmSignUpComponent> = i0.ɵccf('skm-signup',
    i1.skmSignUpComponent,View_skmSignUpComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvdXNlci9zaWdudXAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL3VzZXIvc2lnbnVwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL3VzZXIvc2lnbnVwLmNvbXBvbmVudC50cy5za21TaWduVXBDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L3BlcnNvbmFsL3NrbS9hc3NldHMvYXBwL3VzZXIvc2lnbnVwLmNvbXBvbmVudC50cy5za21TaWduVXBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgICAgICAgICA8aDE+c2lnbiB1cDwvaDE+XG4gICAgICAgICAgICAiLCI8c2ttLXNpZ251cD48L3NrbS1zaWdudXA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsdURBQ2dCO2FBQUE7VUFBQSw0Q0FBSTtNQUFBLGNBQVk7Ozs7b0JDRGhDO01BQUE7YUFBQTtVQUFBOzs7In0=
