/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './base/home.component.ngfactory';
import * as i4 from './base/info/about/about.component.ngfactory';
import * as i5 from './inprogress.component.ngfactory';
import * as i6 from './app.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/platform-browser';
import * as i9 from '@angular/forms';
import * as i10 from '@angular/router';
import * as i11 from './base/home.component';
import * as i12 from './base/info/about/about.component';
import * as i13 from './inprogress.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.skmHomeComponentNgFactory,i4.skmAboutComponentNgFactory,i5.skmInProgressPageNgFactory,
              i6.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i7.NgLocalization,
              i7.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i8.DomSanitizer,
              i8.ɵe,[i8.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i8.DomSanitizer]),
          i0.ɵmpd(4608,i8.HAMMER_GESTURE_CONFIG,i8.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i8.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i8.ɵDomEventsPlugin(p0_0),new i8.ɵKeyEventsPlugin(p1_0),new i8.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i8.DOCUMENT,i8.DOCUMENT,i8.DOCUMENT,i8.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i8.EventManager,i8.EventManager,[i8.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i8.ɵDomSharedStylesHost,i8.ɵDomSharedStylesHost,[i8.DOCUMENT]),
          i0.ɵmpd(4608,i8.ɵDomRendererFactory2,i8.ɵDomRendererFactory2,[i8.EventManager,
              i8.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i8.ɵDomRendererFactory2]),i0.ɵmpd(6144,i8.ɵSharedStylesHost,(null as any),
              [i8.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i8.Meta,i8.Meta,[i8.DOCUMENT]),i0.ɵmpd(4608,
              i8.Title,i8.Title,[i8.DOCUMENT]),i0.ɵmpd(4608,i9.ɵi,i9.ɵi,([] as any[])),
          i0.ɵmpd(5120,i10.ActivatedRoute,i10.ɵf,[i10.Router]),i0.ɵmpd(4608,i10.NoPreloading,
              i10.NoPreloading,([] as any[])),i0.ɵmpd(6144,i10.PreloadingStrategy,
              (null as any),[i10.NoPreloading]),i0.ɵmpd(135680,i10.RouterPreloader,
              i10.RouterPreloader,[i10.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i10.PreloadingStrategy]),i0.ɵmpd(4608,i10.PreloadAllModules,
              i10.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i10.ROUTER_INITIALIZER,
              i10.ɵi,[i10.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i10.ROUTER_INITIALIZER]),i0.ɵmpd(512,i7.CommonModule,i7.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i8.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i10.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i10.ɵg,i10.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i8.ɵc(p0_0,p0_1),i10.ɵh(p1_0)];
              },[[2,i8.NgProbeToken],[2,i0.NgProbeToken],i10.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i8.BrowserModule,i8.BrowserModule,[[3,i8.BrowserModule]]),i0.ɵmpd(512,
              i9.ɵba,i9.ɵba,([] as any[])),i0.ɵmpd(512,i9.FormsModule,i9.FormsModule,
              ([] as any[])),i0.ɵmpd(1024,i10.ɵa,i10.ɵd,[[3,i10.Router]]),i0.ɵmpd(512,
              i10.UrlSerializer,i10.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i10.ChildrenOutletContexts,i10.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i10.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i7.LocationStrategy,
              i10.ɵc,[i7.PlatformLocation,[2,i7.APP_BASE_HREF],i10.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i7.Location,i7.Location,[i7.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,
              i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i10.ROUTES,
              () => {
                return [[{path:'',redirectTo:'/home',pathMatch:'full'},{path:'home',
                    component:i11.skmHomeComponent},{path:'about',component:i12.skmAboutComponent},
                    {path:'inProgress',component:i13.skmInProgressPage},{path:'**',
                        redirectTo:'/home'}]];
              },([] as any[])),i0.ɵmpd(1024,i10.Router,i10.ɵe,[i0.ApplicationRef,i10.UrlSerializer,
              i10.ChildrenOutletContexts,i7.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i10.ROUTES,i10.ROUTER_CONFIGURATION,[2,i10.UrlHandlingStrategy],
              [2,i10.RouteReuseStrategy]]),i0.ɵmpd(512,i10.RouterModule,i10.RouterModule,
              [[2,i10.ɵa],[2,i10.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9wZXJzb25hbC9za20vYXNzZXRzL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
