/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header/header.component.ngfactory';
import * as i2 from './header/header.component';
import * as i3 from '@angular/router';
import * as i4 from './footer/footer.component.ngfactory';
import * as i5 from './footer/footer.component';
import * as i6 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'skm-header',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_skmComponentHeader_0,i1.RenderType_skmComponentHeader)),
      i0.ɵdid(49152,(null as any),0,i2.skmComponentHeader,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(212992,
          (null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,
              i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),1,'skm-footer',([] as any[]),(null as any),
              (null as any),(null as any),i4.View_skmFooterComponent_0,i4.RenderType_skmFooterComponent)),
      i0.ɵdid(49152,(null as any),0,i5.skmFooterComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n\n']))],(_ck,_v) => {
    _ck(_v,4,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i6.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i6.AppComponent> = i0.ɵccf('my-app',
    i6.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9wZXJzb25hbC9za20vYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovcGVyc29uYWwvc2ttL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8c2ttLWhlYWRlcj48L3NrbS1oZWFkZXI+XHJcbjxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cclxuPHNrbS1mb290ZXI+PC9za20tZm9vdGVyPlxyXG5cclxuIiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7YUFBQTtVQUFBLGVBQXlCLHVDQUN6QjtVQUFBO1VBQUEsaUVBQUE7VUFBQTswQ0FBQTtVQUFBLDZCQUErQix1Q0FDL0I7aUJBQUE7Y0FBQTthQUFBO1VBQUEsZUFBeUI7SUFEekI7Ozs7b0JDREE7TUFBQTthQUFBOzs7OyJ9
